# This is a basic workflow to help you get started with Actions

name: FileParser

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest  
    
    # defaults:
      # run:
        # working-directory:  ${{ github.workspace }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: EchoCurrentDirName
        run: |
          Get-ChildItem -Path $PWD
        
      - name: EchoCurrentDirContents
        run:  write-host Get-ChildItem -Path $PWD
          
          
      - name: ReadLimerick
        id: readPoem
        uses: juliangruber/read-file-action@v1
        with:
          path: ./worksRaw/limerick.poem

        
      - name: WriteContent
        run: echo ${{ steps.readPoem.outputs.content }}
